package main.java;

public enum MESSAGETYPE {
	LOGINTOSEND,
	MESSAGETOSEND,
	REQUESTUPDATE,
	DISCONNECT,
	ADD_USER,
	ADD_ACCOUNT,
	REMOVE_ACCOUNT,
	GET_LOG,
	GET_CHATLIST, // ADDED NOVEMBER 28 KA
	CHATLIST_RESPONSE, // ADDED NOVEMBER 28 KA
    ADD_CHAT, // ADDED NOVEMBER 28 KA     
    REMOVE_CHAT, // ADDED NOVEMBER 28 KA
    GETHISTORY, // NOVEMBER 29 JH
    SENDHISTORY, // NOVEMBER 29 JH
    GETPARTICIPANTS, // DECEMBER 2 RP
    SENDPARTICIPANTS // DECEMBER 2 RP   
}
